// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerPilot.Infrastructure.Persistence;

#nullable disable

namespace ServerPilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ServerPilotDbContext))]
    [Migration("20260728221343_AddServerInstances")]
    partial class AddServerInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerPilot.Domain.Agents.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("credential_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("CredentialRevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("credential_revoked_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("machine_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("operating_system");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_version");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("CredentialHash")
                        .IsUnique()
                        .HasDatabaseName("ux_agents_credential_hash");

                    b.HasIndex("UserId", "RegisteredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_agents_user_id_registered_at_id");

                    b.ToTable("agents", null, t =>
                        {
                            t.HasCheckConstraint("ck_agents_trimmed_metadata", "name = btrim(name) AND name <> '' AND machine_name = btrim(machine_name) AND machine_name <> '' AND operating_system = btrim(operating_system) AND operating_system <> '' AND agent_version = btrim(agent_version) AND agent_version <> ''");

                            t.HasCheckConstraint("ck_agents_valid_credential_hash", "credential_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_agents_valid_credential_revoked_at", "credential_revoked_at IS NULL OR credential_revoked_at >= registered_at");

                            t.HasCheckConstraint("ck_agents_valid_last_seen_at", "last_seen_at IS NULL OR last_seen_at >= registered_at");
                        });
                });

            modelBuilder.Entity("ServerPilot.Domain.InstallationTokens.AgentInstallationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_agent_installation_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_installation_tokens_token_hash");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_agent_installation_tokens_user_id_created_at");

                    b.ToTable("agent_installation_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_installation_tokens_single_terminal_state", "used_at IS NULL OR revoked_at IS NULL");

                            t.HasCheckConstraint("ck_agent_installation_tokens_valid_lifetime", "expires_at > created_at");

                            t.HasCheckConstraint("ck_agent_installation_tokens_valid_revoked_at", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_agent_installation_tokens_valid_token_hash", "token_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_agent_installation_tokens_valid_used_at", "used_at IS NULL OR (used_at >= created_at AND used_at < expires_at)");
                        });
                });

            modelBuilder.Entity("ServerPilot.Domain.ServerInstances.ServerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("arguments");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("executable_path");

                    b.Property<int?>("LastProcessId")
                        .HasColumnType("integer")
                        .HasColumnName("last_process_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("process_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("working_directory");

                    b.HasKey("Id")
                        .HasName("pk_server_instances");

                    b.HasIndex("AgentId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_server_instances_agent_id_created_at_id");

                    b.ToTable("server_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_server_instances_trimmed_configuration", "name = btrim(name) AND name <> '' AND executable_path = btrim(executable_path) AND executable_path <> '' AND arguments = btrim(arguments) AND working_directory = btrim(working_directory) AND working_directory <> '' AND process_name = btrim(process_name) AND process_name <> '' AND position('/' in process_name) = 0 AND position(':' in process_name) = 0");

                            t.HasCheckConstraint("ck_server_instances_valid_state", "status BETWEEN 1 AND 7 AND (last_process_id IS NULL OR last_process_id > 0)");

                            t.HasCheckConstraint("ck_server_instances_valid_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("ServerPilot.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ServerPilot.Domain.Agents.Agent", b =>
                {
                    b.HasOne("ServerPilot.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agents_users_user_id");
                });

            modelBuilder.Entity("ServerPilot.Domain.InstallationTokens.AgentInstallationToken", b =>
                {
                    b.HasOne("ServerPilot.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_installation_tokens_users_user_id");
                });

            modelBuilder.Entity("ServerPilot.Domain.ServerInstances.ServerInstance", b =>
                {
                    b.HasOne("ServerPilot.Domain.Agents.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_instances_agents_agent_id");
                });
#pragma warning restore 612, 618
        }
    }
}
